POST http://localhost:3000/job_posts
Content-Type: application/json
Authorization: Bearer ____ACCESS_TOKEN

{

}


###
POST http://localhost:3000/users
Content-Type: application/json

{
  "user": {
    "email": "job.sacha@gmail.com",
    "password": "yourpassword",
    "password_confirmation": "yourpassword"
  }
}


###
POST http://localhost:3000/users
Content-Type: application/json

{
        "user": {
          "email": "christen.den@gmail.com",
          "password": "yourpassword",
          "password_confirmation": "yourpassword"
        }
      }


###
POST http://localhost:3000/users/sign_in
Content-Type: application/json

{
   "user": { 
    "email": "job.sacha@gmail.com",
    "password": "yourpassword"
    }

}

###
POST http://localhost:3000/users/sign_in
Content-Type: application/json

{
   "user": { 
    "email": "job.sacha@gmail.com",
    "password": "yourpassword"
    }

}



###
DELETE  http://localhost:3000/users/sign_out
Authorization: Bearer bca883b1a8caf1f5a6d0







