development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/postbee_api_development' %>
      options:
        server_selection_timeout: 30
  options:
    raise_not_found_error: false


test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://localhost:27017/postbee_api_test' %>
      options:
        server_selection_timeout: 30
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 30

  options:
    raise_not_found_error: false
