# :concurrency: 5
# :queues:
#   - default

# :schedule:
#   job_scraper_worker:
#     # cron: "0 4 * * *"  # Runs every day at 4:00 AM
#     cron: "*/2 * * * *"  # Runs every 2 minutes
#     class: "JobScraperWorker"

:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    job_scraper_worker:
      cron: "*/2 * * * *" # Runs every 2 minutes
      class: "JobScraperJob"
