:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    job_scraper_worker:
      cron: "0 */12 * * *"
      class: "JobScraperJob"

    send_job_recommendations:
      cron: "0 0 * * *"  
      class: "SendJobRecommendationsJob"
