:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    job_scraper_worker:
      cron: "* * * * *"
      class: "JobScraperJob"

    send_job_recommendations:
      cron: "* * * * *"
      # cron: "0 0 1 */4"  # This runs on the first day of every 4 months at midnight
      class: "SendJobRecommendationsJob"
