:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    job_scraper_worker_every_minute:
      cron: "* * * * *"          # Runs every minute
      class: "JobScraperJob"

    job_scraper_worker:             # This runs every 12 hours
      cron: "0 */12 * * *"
      class: "JobScraperJob"

    send_job_recommendations:
      cron: "0 0 * * *"             # Runs every day at midnight
      class: "SendJobRecommendationsJob"