name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
      rabbitmq:  
        image: rabbitmq:3.10-management 
        ports:
          - 5672:5672
          - 15672:15672
    
    env:
      RABBITMQ_URL: amqp://guest:guest@localhost:5672
      MONGODB_URI: mongodb://localhost:27017/postbee_api_test
      RAILS_ENV: test
      SKIP_CUCUMBER: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: false

      - name: Set up dependencies
        run: |
          gem install bundler
          bundle install 

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Cucumber tests
        if: env.SKIP_CUCUMBER != 'true'
        run: bundle exec cucumber

      - name: Run MiniTest tests
        run: bundle exec rake test
        continue-on-error: true