name: CI

on:
  push:
    branches:
      - master
      - feature/set-up-github-actions-16
  pull_request:
    branches:
      - master
      - feature/set-up-github-actions-16
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Check MongoDB logs
        run: docker logs mongo

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Cucumber tests
        run: bundle exec cucumber

      - name: Run MiniTest tests
        run: bundle exec rake test