name: CI

on:
  push:
    branches:
      - master
      - feature/set-up-github-actions-16
  pull_request:
    branches:
      - master
      - feature/set-up-github-actions-16
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
      rabbitmq:  
        image: rabbitmq:3-management 
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "curl -f http://localhost:15672/ || exit 1"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 5
    env:
      RABBITMQ_URL: amqp://guest:guest@localhost:5672
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
     
      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if docker inspect -f '{{.State.Health.Status}}' mongodb; then
              break
            fi
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
      
      - name: Check MongoDB logs
        run: docker logs mongodb || echo "MongoDB container is not available yet."

      - name: Wait for RabbitMQ to be ready
        run: |
          for i in {1..30}; do
            if docker inspect -f '{{.State.Health.Status}}' rabbitmq; then
              break
            fi
            echo "Waiting for RabbitMQ to be ready..."
            sleep 2
          done
      - name: Check RabbitMQ logs
        run: docker logs rabbitmq || echo "RabbitMQ container is not available yet."

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Cucumber tests
        run: bundle exec cucumber

      - name: Run MiniTest tests
        run: bundle exec rake test